export interface Card {
  id: string
  name: string
  popular?: boolean
  type: 'barcode' | 'qrcode'
  country?: Array<string>
  color: string
}

export const POPULAR_CARDS: Card[] = [
  {
    id: 'kaufland',
    name: 'Kaufland',
    type: 'barcode',
    color: '#E4002B',
    popular: true,
  },
  {
    id: 'tesco',
    name: 'Tesco',
    type: 'barcode',
    color: '#00539F',
    popular: true,
  },
  {
    id: 'billa',
    name: 'Billa',
    type: 'barcode',
    color: '#FFD700',
    popular: true,
  },
  {
    id: 'albert',
    name: 'Albert',
    type: 'qrcode',
    color: '#0078D7',
    popular: false,
  },
  {
    id: 'lidl',
    name: 'Lidl',
    type: 'qrcode',
    color: '#00509E',
    popular: true,
  },
  {
    id: 'penny',
    name: 'Penny Market',
    type: 'barcode',
    color: '#E30613',
    popular: false,
  },
  {
    id: 'coopjednota',
    name: 'Coop Jednota',
    type: 'barcode',
    color: '#009245',
    popular: true,
  },
  {
    id: 'teta',
    name: 'TETA',
    type: 'barcode',
    color: '#FFDD00',
    popular: false,
  },
  {
    id: 'dracik',
    name: 'Dráčik',
    type: 'barcode',
    color: '#ED1C24',
    popular: false,
  },
  {
    id: 'kik',
    name: 'KiK',
    type: 'qrcode',
    color: '#E2001A',
    popular: false,
  },
  {
    id: 'sportisimo',
    name: 'Sportisimo',
    type: 'barcode',
    color: '#8CC63F',
    popular: false,
  },
  {
    id: 'nay',
    name: 'NAY',
    type: 'barcode',
    color: '#E6001A',
    popular: false,
  },
  {
    id: 'metro',
    name: 'METRO',
    type: 'qrcode',
    color: '#003876',
    popular: false,
  },
  {
    id: 'decathlon',
    name: 'Decathlon',
    type: 'barcode',
    color: '#0082C3',
    popular: false,
  },
  {
    id: 'slovnaft',
    name: 'Slovnaft',
    type: 'barcode',
    color: '#F39200',
    popular: false,
  },
  {
    id: 'albi',
    name: 'ALBI',
    type: 'barcode',
    color: '#D41E28',
    popular: false,
  },
  {
    id: 'alltoys',
    name: 'ALLTOYS',
    type: 'barcode',
    color: '#EE3439',
    popular: false,
  },
  {
    id: 'aupark',
    name: 'Aupark',
    type: 'qrcode',
    color: '#8BC53F',
    popular: false,
  },
  {
    id: 'bata',
    name: 'Baťa',
    type: 'barcode',
    color: '#D62129',
    popular: false,
  },
  {
    id: 'benu',
    name: 'BENU',
    type: 'barcode',
    color: '#00A69C',
    popular: false,
  },
  {
    id: 'gopass',
    name: 'Gopass',
    type: 'qrcode',
    color: '#231F20',
    popular: false,
  },
  {
    id: 'ikea',
    name: 'IKEA Family',
    type: 'barcode',
    color: '#0058A3',
    popular: false,
  },
  {
    id: 'martinus',
    name: 'Martinus',
    type: 'qrcode',
    color: '#F58220',
    popular: false,
  },
  {
    id: 'mcdonalds',
    name: 'McDonald´s',
    type: 'qrcode',
    color: '#DB0007',
    popular: false,
  },
  {
    id: 'mobelix',
    name: 'Möbelix',
    type: 'barcode',
    color: '#E30613',
    popular: false,
  },
  {
    id: 'obi',
    name: 'OBI',
    type: 'barcode',
    color: '#F68A1E',
    popular: false,
  },
  {
    id: 'pantarhei',
    name: 'Panta Rhei',
    type: 'barcode',
    color: '#8D1B3D',
    popular: false,
  },
  
];